### ISSUE TITLE
Github Codespace could not be created if Codespace was prebuild 

### ISSUE THREAD

**Issue by vkrivtsov-stuzo** [devcontainers/spec#343]
Hi,

I've faced with issue I cannot open Github Codespace if this codespace was built by prebuild feature. it works in case of opening Codespace without prior using prebuild feature.

```bash
Configuration starting...
Checking out...
Creating container...
$ devcontainer up --id-label Type=codespaces --workspace-folder /var/lib/docker/codespacemount/workspace/hello-world-repo --mount type=bind,source=/.codespaces/agent/mount/cache,target=/vscode --user-data-folder /var/lib/docker/codespacemount/.persistedshare --container-data-folder .vscode-remote/data/Machine --container-system-data-folder /var/vscode-remote --log-level trace --log-format json --update-remote-user-uid-default never --mount-workspace-git-root false --omit-config-remote-env-from-metadata --skip-non-blocking-commands --skip-post-create --expect-existing-container --config "/var/lib/docker/codespacemount/workspace/hello-world-repo/.devcontainer/full/devcontainer.json" --override-config /root/.codespaces/shared/merged_devcontainer.json --default-user-env-probe loginInteractiveShell --container-session-data-folder /workspaces/.codespaces/.persistedshare/devcontainers-cli/cache --secrets-file /root/.codespaces/shared/user-secrets-envs.json
[255 ms] @devcontainers/cli 0.52.1. Node.js v18.17.1. linux 6.2.0-1016-azure x64.
[6033 ms] Start: Run: docker-compose -f /var/lib/docker/codespacemount/workspace/hello-world-repo/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml config
[535 ms] Stop: Run: docker-compose -f /var/lib/docker/codespacemount/workspace/hello-world-repo/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml config
[6607 ms] Start: Run: docker-compose --project-name hello-world-repo -f /var/lib/docker/codespacemount/workspace/hello-world-repo/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.build-1700508243775.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.containerFeatures-1700508335239.yml up -d --no-recreate postgres redis rabbitmq devcontainer
Building devcontainer
ERROR: could not find /tmp/devcontainercli-root/container-features/0.52.1-1700508240689: stat /tmp/devcontainercli-root/container-features/0.52.1-1700508240689: no such file or directory
ERROR: Service 'devcontainer' failed to build : Build failed
[1161 ms] Stop: Run: docker-compose --project-name hello-world-repo -f /var/lib/docker/codespacemount/workspace/hello-world-repo/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.build-1700508243775.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.containerFeatures-1700508335239.yml up -d --no-recreate postgres redis rabbitmq devcontainer
Error: Command failed: docker-compose --project-name hello-world-repo -f /var/lib/docker/codespacemount/workspace/hello-world-repo/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.build-1700508243775.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.containerFeatures-1700508335239.yml up -d --no-recreate postgres redis rabbitmq devcontainer
{"outcome":"error","message":"Command failed: docker-compose --project-name hello-world-repo -f /var/lib/docker/codespacemount/workspace/hello-world-repo/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.build-1700508243775.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.containerFeatures-1700508335239.yml up -d --no-recreate postgres redis rabbitmq devcontainer","description":"An error occurred starting Docker Compose up.","containerId":"5b486fc972d8b432632d37c0737a3b3101e98031a6b853707e7cfb7c4254ffe2"}
    at sAA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:427:3165)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async oAA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:409:3170)
    at async NAA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:479:3833)
    at async vC (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:479:4775)
    at async etA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:613:10941)
    at async AtA (/usr/lib/node_modules/@devcontainers/cli/dist/spec-node/devContainersSpecCLI.js:613:10682)
devcontainer process exited with exit code 1
Failed to create container.
Error: Command failed: docker-compose --project-name hello-world-repo -f /var/lib/docker/codespacemount/workspace/hello-world-repo/docker-compose.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose.codespaces.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.build-1700508243775.yml -f /var/lib/docker/codespacemount/.persistedshare/docker-compose/docker-compose.devcontainer.containerFeatures-1700508335239.yml up -d --no-recreate postgres redis rabbitmq devcontainer
Error code: 1302 (UnifiedContainersErrorFatalCreatingContainer)
Container creation failed.

Creating recovery container.
```

**Comment by samruddhikhandale** [comment]
Hi 👋 

Thanks for reporting, we recently heard similar issues for Codespaces and are currently looking into it.
Thanks for your patience.

**Comment by vkrivtsov-stuzo** [comment]
@samruddhikhandale btw Github CodeSpace continue to use cached images from prebuilt feature even I've removed prebuild config so particular codespace turns out into recovery mode always without to build devcontainer from scratch.

**Comment by samruddhikhandale** [comment]
@vkrivtsov-stuzo have you looked at https://docs.github.com/en/codespaces/prebuilding-your-codespaces/managing-prebuilds#deleting-a-prebuild-configuration? 

> Deleting a prebuild configuration also deletes all previously created prebuilds for that configuration. As a result, shortly after you delete a configuration, prebuilds generated by that configuration will no longer be available when you create a new codespace.
>
> After you delete a prebuild configuration, workflow runs for that configuration that have been queued or started will still run. They will be listed in the workflow run history, along with previously completed workflow runs.

I think it takes some time to reflect, however, if you create a new codespace after deleting prebuild configs, then you shouldn't get a prebuilt codespace.

Side note: If you run `Codespaces: Full rebuild container` command from the command palette, then it should also fix the issue for you.

**Comment by samruddhikhandale** [comment]
Update: It's looking like a bad image upgrade on the prebuild action runners, we're working on reverting to the previous working image.

**Comment by samruddhikhandale** [comment]
The image deployment has completed and this issue should now be resolved. You will need to rerun/trigger the prebuild action to mitigate this issue. All the creations using the new prebuilds should be successful.
